import {useEffect,useState} from 'react';
import {AnimatePresence,motion} from 'framer-motion';
import {Link,useLocation} from 'react-router-dom';
import {Menu,X,ArrowUpRight,ChevronDown} from 'lucide-react';
import {nav} from '../../data/navigation';
import Container from '../ui/Container';

export default function Header(){const [open,setOpen]=useState(false);const [mega,setMega]=useState(null);const [scrolled,setScrolled]=useState(false);const loc=useLocation();useEffect(()=>{const f=()=>setScrolled(scrollY>18);f();addEventListener('scroll',f,{passive:true});return()=>removeEventListener('scroll',f)},[]);useEffect(()=>{setOpen(false);setMega(null)},[loc.pathname,loc.hash]);useEffect(()=>{document.body.style.overflow=open?'hidden':'';return()=>document.body.style.overflow=''},[open]);const active=i=>loc.pathname===i.to||loc.pathname.startsWith(i.to+'/')||(i.to==='/ar-ge'&&loc.pathname.startsWith('/teknolojiler'));
return <header className={`fixed inset-x-0 top-0 z-50 border-b transition-all ${scrolled?'border-ink/12 bg-paper/95 backdrop-blur-xl':'border-ink/10 bg-paper/90 backdrop-blur-md'}`}><Container><div className={`flex items-center justify-between transition-all ${scrolled?'h-[70px]':'h-[82px]'}`}><Link to="/" className="flex items-center gap-3"><div className="grid size-8 place-items-center border border-green text-[12px] font-black text-green">T</div><div><b className="block text-[15px] tracking-[-.03em]">TAMİS</b><span className="block text-[7px] font-bold uppercase tracking-[.22em] text-ink/35">Teknoloji</span></div></Link><nav className="hidden items-center gap-7 xl:flex">{nav.map((i)=><button key={i.label} onMouseEnter={()=>setMega(i)} className={`group relative flex items-center gap-1.5 py-7 text-[9px] font-bold uppercase tracking-[.14em] ${active(i)?'text-green':'text-ink/62'}`}>{i.label}<ChevronDown size={11}/><span className={`absolute bottom-4 left-0 h-px bg-green transition-all ${active(i)?'w-full':'w-0 group-hover:w-full'}`}/></button>)}</nav><div className="hidden items-center gap-6 xl:flex"><span className="h-5 w-px bg-ink/15"/><Link to="/iletisim" className="group flex items-center gap-2 text-[9px] font-bold uppercase tracking-[.16em]">İletişim <ArrowUpRight size={12} className="transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5"/></Link></div><button className="grid size-10 place-items-center xl:hidden" onClick={()=>setOpen(!open)} aria-label="Menü">{open?<X/>:<Menu/>}</button></div></Container>
<AnimatePresence>{mega&&<motion.div initial={{opacity:0,y:-8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}} onMouseLeave={()=>setMega(null)} className="hidden border-t border-ink/10 bg-paper xl:block"><Container className="grid grid-cols-12 py-9"><div className="col-span-3"><span className="micro-label">Navigation / TAMİS</span><h3 className="mt-4 text-3xl font-medium tracking-[-.04em]">{mega.label}</h3></div><div className="col-span-9 grid grid-cols-3 gap-px bg-ink/10 border border-ink/10">{mega.children?.map(([label,to],n)=><Link key={to} to={to} className="group bg-paper p-6 transition-colors hover:bg-white"><span className="text-[8px] font-bold tracking-[.18em] text-green">0{n+1}</span><div className="mt-8 flex items-end justify-between"><span className="text-lg font-medium">{label}</span><ArrowUpRight size={14} className="text-ink/25 group-hover:text-green"/></div></Link>)}</div></Container></motion.div>}</AnimatePresence>
<AnimatePresence>{open&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-x-0 bottom-0 top-[70px] overflow-y-auto bg-green text-white xl:hidden"><div className="px-5 py-8"><p className="text-[8px] font-bold uppercase tracking-[.2em] text-white/35">TAMİS / Navigation</p>{nav.map((i,n)=><div key={i.label} className="border-b border-white/12"><Link to={i.to} className="flex items-center justify-between py-6"><span className="text-2xl font-medium tracking-[-.04em]">{i.label}</span><span className="text-[9px] text-white/35">0{n+1}</span></Link><div className="-mt-2 pb-5">{i.children?.map(([l,t])=><Link key={t} to={t} className="mr-5 inline-block py-2 text-[10px] uppercase tracking-[.12em] text-white/48">{l}</Link>)}</div></div>)}<Link to="/iletisim" className="mt-8 flex items-center justify-between border border-white/20 p-5 text-xs font-bold uppercase tracking-[.16em]">İletişim <ArrowUpRight size={14}/></Link></div></motion.div>}</AnimatePresence></header>}
