import { Hero, Statement, DarkBand, Cards } from "../components/ui/PageKit";
import Container from "../components/ui/Container";
import { Link } from "react-router-dom";
import { ArrowUpRight } from "lucide-react";
const items=[
 {id:"cnc",kicker:"Hassas İmalat",title:"CNC Talaşlı İmalat",copy:"4 eksen ve 3 eksen CNC dik işleme, CNC tornalama ve üniversal tornalama altyapısıyla hassas parça imalatı."},
 {id:"prototipleme",kicker:"Mühendislik",title:"Tasarım & Prototipleme",copy:"Teknik ihtiyaçların tasarım çalışmalarından fiziksel prototipe ve üretilebilir çözüme taşınması."},
 {id:"derin-delme",kicker:"4000 × 800 mm",title:"Çelik Karot Derin Delme",copy:"4 metre üniversal torna altyapısıyla çelik karot derin delme kabiliyeti."},
 {id:"pres",kicker:"160 Ton",title:"Hidrolik Pres",copy:"160 ton hidrolik pres kapasitesiyle üretim süreçlerini destekleyen pres altyapısı."},
];
const materials=["4140 Çelik","8620 Çelik","1040 Çelik","CK45 Çelik","Hardox 450–500","7000 Seri Alüminyum","316 Paslanmaz Çelik"];
export default function Capabilities(){return <main><Hero eyebrow="Yetkinlikler" title="Üretilebilir" accent="çözümler." copy="TAMİS, talaşlı imalat ile tasarım ve prototipleme kabiliyetlerini hassas üretim odağında bir araya getirir." media="MANUFACTURING / CAPABILITIES" mediaSrc="/media/real/cnc-isleme.jpeg"/><Statement eyebrow="Üretim Yaklaşımı" title="Teknik ihtiyaçtan" accent="fiziksel çıktıya." copy="Tasarım, prototipleme ve imalat; birbirinden kopuk adımlar değil, üretilebilir sonuca ulaşan tek bir mühendislik zinciridir."/><section className="border-y rule bg-paper py-20 md:py-28"><Container><Cards items={items}/></Container></section><section id="malzemeler" className="bg-white py-24 md:py-32"><Container><div className="grid gap-12 lg:grid-cols-12"><div className="lg:col-span-4"><p className="eyebrow">İşlenen Hammaddeler</p><h2 className="mt-8 text-5xl font-medium leading-[.92] tracking-[-.055em] md:text-6xl">Malzemeyi tanı.<br/><span className="text-green">Prosesi yönet.</span></h2></div><div className="lg:col-span-8"><div className="border-t rule">{materials.map((m,i)=><div key={m} className="grid grid-cols-[1fr_auto] items-center border-b rule py-5"><span className="text-xl font-medium">{m}</span><span className="micro-label text-green">{String(i+1).padStart(2,"0")}</span></div>)}</div></div></div></Container></section><DarkBand eyebrow="Üretim Altyapısı" title="Kabiliyet, altyapıyla güçlenir."><div className="flex flex-col gap-7 md:flex-row md:items-end md:justify-between"><p className="max-w-2xl text-base leading-8 text-white/58">Makine parkı; CNC dik işleme, tornalama, derin delme ve hidrolik pres kabiliyetlerini ölçülebilir üretim kapasitesiyle bir araya getirir.</p><Link to="/uretim-altyapisi" className="btn btn-light shrink-0">Altyapıyı incele <ArrowUpRight size={13}/></Link></div></DarkBand></main>}
