import {motion} from 'framer-motion';
import {ArrowDown,ArrowUpRight,MoveRight} from 'lucide-react';
import {Link} from 'react-router-dom';
import Container from '../components/ui/Container';

const caps=[
 ['01','Savunma Sistemleri','Sistem seviyesi mühendislik, entegrasyon ve doğrulama yaklaşımı.','16:10 / SAVUNMA'],
 ['02','Elektronik Teknolojiler','Gömülü sistemler, kontrol elektroniği ve elektronik tasarım yetkinlikleri.','16:10 / ELEKTRONİK'],
 ['03','Otonom Sistemler','Algılama, karar ve kontrol katmanlarını bir araya getiren platform teknolojileri.','16:10 / OTONOM'],
 ['04','Yazılım & Yapay Zekâ','Kritik sistemler için güvenilir yazılım ve veri odaklı çözümler.','16:10 / YAZILIM']
];
const reveal={initial:{opacity:0,y:28},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.18},transition:{duration:.75,ease:[.16,1,.3,1]}};
export default function Home(){return <main>
<section className="relative min-h-screen overflow-hidden border-b border-ink/12 pt-[82px]"><Container className="grid min-h-[calc(100vh-82px)] gap-8 py-8 lg:grid-cols-[.82fr_1.18fr] lg:items-stretch lg:py-10"><motion.div {...reveal} className="flex flex-col justify-between py-3 lg:py-8"><div className="flex items-center gap-3"><span className="h-px w-9 bg-green"/><span className="eyebrow text-green">Türkiye · İleri Teknoloji</span></div><div className="py-16 lg:py-8"><p className="mb-6 text-sm font-semibold text-green">TAMİS Teknoloji</p><h1 className="text-[clamp(4rem,8.5vw,9rem)] font-semibold leading-[.82] tracking-[-.075em]">Fikirden<br/>sisteme.</h1><p className="mt-8 max-w-lg text-lg leading-8 text-ink/58">Yüksek katma değerli sistemler için araştırma, mühendislik ve teknoloji geliştirme.</p><div className="mt-10 flex flex-wrap gap-3"><Link to="/yetkinlikler" className="btn-primary">Yetkinlikleri keşfet <ArrowUpRight size={15}/></Link><Link to="/kurumsal" className="btn-secondary">TAMİS hakkında</Link></div></div><div className="flex items-center gap-3 text-[10px] font-bold uppercase tracking-[.18em] text-ink/40"><ArrowDown size={14}/> Keşfetmek için kaydır</div></motion.div><div className="media-placeholder hero-media"><span>HERO PHOTO / FILM</span><small>Desktop 16:9 · Mobile 4:5<br/>Ürün / tesis / mühendislik ana görseli</small><div className="media-code">MEDIA 01</div></div></Container></section>

<section className="bg-white py-24 md:py-36"><Container><motion.div {...reveal} className="grid gap-14 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">01 / TAMİS</p><div className="media-placeholder mt-10 aspect-[4/5] max-w-sm"><span>ENGINEERING PHOTO</span><small>4:5 portrait</small></div></div><div className="lg:pt-20"><h2 className="max-w-5xl text-4xl font-medium leading-[1.03] tracking-[-.055em] md:text-7xl">Teknolojiyi yalnızca kullanmıyoruz. <span className="text-green">Geliştiriyoruz.</span></h2><p className="mt-9 max-w-2xl text-base leading-8 text-ink/55">Araştırma, tasarım, prototipleme, doğrulama ve sistem entegrasyonunu aynı teknoloji vizyonunun parçaları olarak ele alan bütünleşik bir mühendislik yaklaşımı.</p><Link to="/kurumsal" className="mt-9 inline-flex items-center gap-3 border-b border-ink pb-2 text-xs font-bold uppercase tracking-[.15em]">Kurumsal yaklaşım <ArrowUpRight size={15}/></Link></div></motion.div></Container></section>

<section className="border-y border-ink/12 py-24 md:py-32"><Container><div className="mb-14 flex items-end justify-between"><div><p className="eyebrow">02 / Yetkinlikler</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.05em] md:text-6xl">Teknoloji alanları</h2></div><Link className="hidden items-center gap-3 text-xs font-bold uppercase tracking-[.15em] md:flex" to="/yetkinlikler">Tümünü gör <MoveRight size={17}/></Link></div><div className="grid gap-10 lg:grid-cols-[.95fr_1.05fr]"><div>{caps.map(([n,t,d])=><motion.div {...reveal} key={n} className="group grid gap-3 border-t border-ink/18 py-7 md:grid-cols-[55px_1fr]"><span className="text-xs font-bold text-green">{n}</span><div><h3 className="text-2xl font-medium tracking-[-.035em] md:text-3xl">{t}</h3><p className="mt-3 max-w-lg text-sm leading-7 text-ink/50">{d}</p></div></motion.div>)}</div><div className="media-placeholder sticky top-28 min-h-[560px]"><span>CAPABILITY PHOTO</span><small>16:10 landscape<br/>Hover ile kategori görseli değişecek</small><div className="media-code">MEDIA 02</div></div></div></Container></section>

<section className="bg-[#e9eee9] py-24 md:py-36"><Container><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">03 / Öne çıkan sistem</p><h2 className="mt-5 text-4xl font-semibold tracking-[-.05em] md:text-6xl">Ürün vitrini için hazır.</h2><p className="mt-7 max-w-md text-sm leading-7 text-ink/52">Gerçek ürün ve kamuya açık bilgiler hazır olduğunda bu alan TAMİS'in öne çıkan sistemini güçlü bir ürün renderı ile sunacak.</p><Link to="/urunler" className="mt-8 inline-flex items-center gap-3 text-xs font-bold uppercase tracking-[.15em]">Ürünleri incele <ArrowUpRight size={15}/></Link></div><div className="media-placeholder aspect-[16/10] min-h-[420px]"><span>FEATURED PRODUCT RENDER</span><small>16:10 / transparent render veya stüdyo çekimi</small><div className="media-code">PRODUCT 01</div></div></div></Container></section>

<section className="bg-white py-24 md:py-36"><Container><p className="eyebrow">04 / Mühendislik süreci</p><div className="mt-12 grid border-y border-ink/15 md:grid-cols-5">{['Araştırma','Tasarım','Prototip','Doğrulama','Entegrasyon'].map((x,i)=><div key={x} className="border-b border-ink/15 py-8 md:border-b-0 md:border-r md:px-6 first:md:pl-0 last:md:border-r-0"><span className="text-xs font-bold text-green">0{i+1}</span><h3 className="mt-16 text-xl font-medium tracking-[-.03em]">{x}</h3><p className="mt-3 text-xs leading-6 text-ink/45">Sistem yaşam döngüsünün birbirini besleyen mühendislik aşaması.</p></div>)}</div></Container></section>

<section className="py-24 md:py-36"><Container><motion.div {...reveal} className="grid gap-12 lg:grid-cols-2"><div className="media-placeholder min-h-[560px]"><span>R&D / LAB PHOTO</span><small>4:5 veya 3:4<br/>Laboratuvar · mühendis · prototip</small><div className="media-code">MEDIA 03</div></div><div className="flex flex-col justify-center lg:pl-10"><p className="eyebrow">05 / Araştırma & Geliştirme</p><h2 className="mt-5 text-5xl font-medium leading-[.98] tracking-[-.055em] md:text-7xl">Yarının<br/>gereksinimleri için.</h2><p className="mt-8 max-w-lg text-base leading-8 text-ink/55">Bugünün ihtiyaçlarını karşılamanın ötesinde, gelecekte ihtiyaç duyulacak teknolojileri bugünden geliştirmeyi hedefleyen uzun vadeli bir yaklaşım.</p><Link to="/ar-ge" className="mt-9 inline-flex w-fit items-center gap-3 border-b border-ink pb-2 text-xs font-bold uppercase tracking-[.15em]">Ar-Ge yaklaşımı <ArrowUpRight size={15}/></Link></div></motion.div></Container></section>

<section className="bg-white py-24 md:py-32"><Container><div className="grid gap-12 lg:grid-cols-[1fr_1.1fr]"><div><p className="eyebrow">06 / Kurumsal</p><h2 className="mt-5 max-w-xl text-4xl font-semibold tracking-[-.05em] md:text-6xl">Mühendislik odağında büyüyen teknoloji şirketi.</h2><p className="mt-7 max-w-lg text-sm leading-7 text-ink/52">Kurumsal fotoğraf, tesis ve ekip içerikleri hazır olduğunda bu bölüm TAMİS'in ölçeğini ve çalışma kültürünü anlatacak.</p></div><div className="media-placeholder aspect-[16/9]"><span>FACILITY / TEAM PHOTO</span><small>16:9 corporate photography</small><div className="media-code">MEDIA 04</div></div></div></Container></section>

<section className="px-3 pb-3 md:px-6 md:pb-6"><div className="bg-green text-white"><Container className="py-20 md:py-28"><p className="eyebrow text-white/50">07 / İletişim</p><div className="mt-8 flex flex-col gap-10 md:flex-row md:items-end md:justify-between"><h2 className="max-w-4xl text-5xl font-medium leading-[.95] tracking-[-.055em] md:text-8xl">Geleceğin teknolojisini birlikte geliştirelim.</h2><Link to="/iletisim" className="inline-flex shrink-0 items-center gap-3 border border-white/35 px-6 py-4 text-xs font-bold uppercase tracking-[.15em] transition hover:bg-white hover:text-green">İletişim <ArrowUpRight size={16}/></Link></div></Container></div></section>
</main>}
