import { Hero, Statement, DarkBand } from "../components/ui/PageKit";
import Container from "../components/ui/Container";
const machines=[
 ["CNC Dik İşleme","4 eksen + 3 eksen","1000 × 600"],
 ["CNC Torna","10 inç","1000 mm × 10 inç"],
 ["Üniversal Torna & Derin Delme","4 metre","4000 × 800 mm"],
 ["Üniversal Torna","1,5 metre","1500 × 350 mm"],
 ["Hidrolik Pres","1 adet","160 ton"],
];
export default function Infrastructure(){return <main><Hero eyebrow="Üretim Altyapısı" title="Makine parkı." accent="Ölçülebilir kapasite." copy="CNC dik işleme, CNC ve üniversal tornalama, çelik karot derin delme ve hidrolik pres altyapısı." media="PRODUCTION / MACHINE PARK" videoSrc="/media/real/uretim.mp4"/><Statement eyebrow="Üretim" title="Hassas imalat için" accent="somut altyapı." copy="Farklı parça geometrileri ve üretim ihtiyaçları için işleme, tornalama, derin delme ve pres kabiliyetleri aynı üretim yapısında buluşur."/><section id="makine-parki" className="bg-white py-24 md:py-32"><Container><div className="flex items-end justify-between gap-6"><div><p className="eyebrow">Makine Parkı</p><h2 className="mt-7 text-5xl font-medium tracking-[-.055em]">Kapasite tablosu.</h2></div><p className="micro-label hidden md:block">TAMİS / PRODUCTION</p></div><div className="mt-12 border-t rule">{machines.map(([name,type,cap])=><div key={name+type} className="grid gap-4 border-b rule py-7 md:grid-cols-12 md:items-center"><h3 className="text-2xl font-medium tracking-[-.04em] md:col-span-5">{name}</h3><p className="micro-label md:col-span-3">{type}</p><p className="text-2xl font-medium tracking-[-.04em] text-green md:col-span-4 md:text-right">{cap}</p></div>)}</div></Container></section><section className="bg-paper py-24"><Container><div className="grid gap-5 md:grid-cols-2"><div className="media min-h-[520px]"><img src="/media/real/universal-torna.jpeg" alt="TAMİS üniversal torna" className="absolute inset-0 h-full w-full object-cover"/><div className="media-shade"/><span className="media-label !text-white">TORNALAMA</span></div><div className="media min-h-[520px]"><img src="/media/real/islenmis-parca.jpeg" alt="TAMİS işlenmiş metal parça" className="absolute inset-0 h-full w-full object-cover"/><div className="media-shade"/><span className="media-label !text-white">İŞLENMİŞ PARÇA</span></div></div></Container></section><DarkBand eyebrow="Kalite Kontrol" title="Ölçüm, üretimin parçasıdır."><div id="kalite" className="grid gap-10 md:grid-cols-2"><div className="border-t border-white/20 pt-6"><p className="micro-label !text-white/45">Boyutsal Kontrol</p><h3 className="mt-4 text-3xl font-medium tracking-[-.04em]">CMM Ölçüm Cihazı</h3><p className="mt-4 max-w-md text-sm leading-7 text-white/52">Koordinat ölçüm altyapısıyla üretim sonrası boyutsal kalite kontrol süreçleri desteklenir.</p></div><div className="border-t border-white/20 pt-6"><p className="micro-label !text-white/45">Hassas Kontrol</p><h3 className="mt-4 text-3xl font-medium tracking-[-.04em]">Yüksek Hassasiyetli Ölçüm</h3><p className="mt-4 max-w-md text-sm leading-7 text-white/52">Yüksek hassasiyetli ölçüm ekipmanları üretim kontrol süreçlerinin bir parçasıdır.</p></div></div></DarkBand></main>}
